service: serverless-example 

plugins:
  - serverless-pseudo-parameters
  - serverless-aws-alias
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:profile, 'default'}

  deploymentBucket: serverless-deployments-${self:provider.stage}
  role: arn:aws:iam::#{AWS::AccountId}:role/service-role/basic_lambda_execution

package:
  include:
    - handler.js

custom:
  customDomain:
    domainName: ${opt:domain-name, 'example.dikanski.org'}
    stage: ${self:provider.alias}
    certificateName: ${opt:certificate-name, '*.dikanski.org'}
    createRoute53Record: ${opt:route53, 'true'}
    endpointType: 'regional'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

