AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample CF Template for Creating API Gateway with Lambda integration.'
Resources:
  # The API Gateway itself
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: 'CF Test API'
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: test-cf-v1
  # Resource /tests
  ApiGatewayResourceTests:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: tests
      RestApiId: !Ref ApiGatewayRestApi
  # Resource /tests/{tests}
  ApiGatewayResourceTestsTest:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiGatewayResourceTests
      PathPart: '{tests}'
      RestApiId: !Ref ApiGatewayRestApi
  # HttpMethod GET /tests
  ApiGatewayMethodTestsGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceTests
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
  # HttpMethod POST /tests
  ApiGatewayMethodTestsPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceTests
      HttpMethod: POST
      AuthorizationType: NONE
      RequestModels:
          'application/json': !Ref ApiGatewayModelTest
      Integration:
        Type: MOCK
        PassthroughBehavior: NEVER
        RequestTemplates:
          'application/json': '{"statusCode": 200}'
        IntegrationResponses:
          -
            StatusCode: 200
            ResponseTemplates:
              'application/json': '{"id": 2}'
      MethodResponses:
        -
          StatusCode: 200
  # Request object for POST /tests
  ApiGatewayModelTest:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: application/json
      Description: "A Test"
      Name: Test
      RestApiId: !Ref ApiGatewayRestApi
      Schema:
        "$schema": "http://json-schema.org/draft-04/schema#" 
        title: ATest
        type: object
        properties:
          name:
            type: string
          description:
            type: string
  ApiGatewayDeploymentDev:
    DependsOn:
      - ApiGatewayMethodTestsGet
      - ApiGatewayMethodTestsPost
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: 'Dev Deployment 1'
      RestApiId: !Ref ApiGatewayRestApi
  ApiGatewayDeploymentDev2:
    DependsOn:
      - ApiGatewayMethodTestsGet
      - ApiGatewayMethodTestsPost
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: 'Dev Deployment 2'
      RestApiId: !Ref ApiGatewayRestApi
  ApiGatewayStageDev:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiGatewayDeploymentDev2
      Description: 'Dev Stage'
      RestApiId: !Ref ApiGatewayRestApi
      StageName: 'Dev'
      CanarySetting:
#        DeploymentId: !Ref ApiGatewayDeploymentDevCanary
#        PercentTraffic: 50

